### ISSUE TITLE
Error on setup.

### ISSUE THREAD

**Issue by heyimnikolai** [Timeraa/YT-Presence#12]
Soo I recently got the Windows version of YT Presence, and I got the extension for Chrome and the setup itself. It was working a bit fine when I first installed it, but there was a problem. An error had occurred while installing. I saw the log for it on notepad, and probably it was my Discord Canary or PTB that was getting into the way. When I uninstalled both of those, I started the installation back up again, and a different error occurred. This time, it's an installation has failed error. How do I fix this and is there a way I can do to fix it? I'd appreciate it if you reply.  Thanks.

~ Nikolai S.

P.S: I am on Chrome and my OS is Windows 10, I dunno the version but it's okay though.

**Comment by Timeraa** [comment]
Try going into the apps section on windows and check if yt presence isremoved

**Comment by heyimnikolai** [comment]
Yeah, it's already removed.

**Comment by heyimnikolai** [comment]
I just saw it on my start menu.

**Comment by Timeraa** [comment]
Hm, try running it again and maybe restart your PC?

**Comment by heyimnikolai** [comment]
Apparently, I deleted the application and the installation. I reinstalled it.

**Comment by heyimnikolai** [comment]
(I meant as in, the installation.)

**Comment by Timeraa** [comment]
Any errors whatsoever? (You can join the YT Presence guild too 
https://discord.gg/Kw7Wan)

**Comment by heyimnikolai** [comment]
Yeah, it happens everytime I open it up.

(btw the invite for the Discord is expired lol)

**Comment by Timeraa** [comment]
Really weird try this link 
https://discord.gg/KvYqNT and give me the error you get
