### ISSUE TITLE
Firewall popup when starting YT Presence

### ISSUE THREAD

**Issue by TheRealJan** [Timeraa/YT-Presence#13]
Hey! My PC says of itself that I should not start the app .... I do not believe that this is a VIrus but why this app needs firewall rights and I have not used a virus program

**Comment by Timeraa** [comment]
Its because its connecting to your localhost

**Comment by TheRealJan** [comment]
Why?

**Comment by Timeraa** [comment]
Because the extension extracts the information from YouTube, Netflix... and sends that data to the localhost:3020 and the Application receives the data from there and then sets your Presence on Discord.

**Comment by Timeraa** [comment]
If you need prove:
Extension: https://github.com/Timeraa/YT-Presence/blob/master/Extension/presences/YouTube.js#L13

Application: https://github.com/Timeraa/YT-Presence/blob/master/src/presenceHandler.js#L41
