### ISSUE TITLE
How to install it on windows?

### ISSUE THREAD

**Issue by Igreky** [Timeraa/YT-Presence#3]
There is no .exe file
Is it possible to install it differently?

**Comment by PoorPocketsMcNewHold** [comment]
[There is.](https://github.com/Timeraa/YT-Presence/releases)

**Comment by Timeraa** [comment]
Yeah sorry for that somewhat bad documentation, i am working hard on a proper installer for Windows and getting the actual extension onto the chrome Web Store.

Closing this issue for now
