### ISSUE TITLE
A JavaScript Error

### ISSUE THREAD

**Issue by kattomil** [Timeraa/YT-Presence#4]
**Describe the bug**
It just shows up an error message

**To Reproduce**
Every step from the extension and windows installation then running the program

**Expected behavior**
The Program to work

**Screenshots**
![image](https://user-images.githubusercontent.com/24627356/44956378-c9152380-aecb-11e8-9cb6-9ee92388be4a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version Latest

**Additional context**
I dunno why it isnt working

**Comment by Timeraa** [comment]
This happens when the program runs twice (Atleast for me) Please open it once and look if its running.

**Comment by EmilR0** [comment]
yeah it was this indeed but now doesnt even work. It said "Youtube" and "Searching for a video" but after I clicked on a video, the presence dissapeared.
![image](https://user-images.githubusercontent.com/24627356/45366020-7b449d80-b5e6-11e8-897c-a3c4f5eae670.png)
![image](https://user-images.githubusercontent.com/24627356/45366044-87c8f600-b5e6-11e8-9cef-7656667e7089.png)

**Comment by Timeraa** [comment]
Hm, i will work on the next version as fast as possible. Since this version is basically a "Make it work" version.

**Comment by Timeraa** [comment]
Fixed in Version 1.0
