### ISSUE TITLE
missing person

### ISSUE THREAD

**Issue by MrAlexEsisteGia** [Timeraa/YT-Presence#9]
![image](https://user-images.githubusercontent.com/24595840/45696824-b3a72700-bb64-11e8-933c-773a86015da2.png)
there is "redstonedaedalus" in the "popup.html" of the extension but it does not show up when you click the tray icon
![image](https://user-images.githubusercontent.com/24595840/45697029-20babc80-bb65-11e8-9550-6e2c5850c119.png)

**Comment by Timeraa** [comment]
Well its not really missing, He and i originally started the idea but he only showed me how i could send data from the extension to the app. He decided to work on his other projects. But this GUI changed completely in Version 1.0. (Hoping to finish it in the next days) And the GUI in the extension was something i forgot to delete when i released that version .
